### ISSUE TITLE
on clicking links in `top charts`, Its playing only baarish song

### ISSUE THREAD

**Issue by ankitjain28may** [himanshukhosla123/gaana.com#1]

**Comment by himanshukhosla123** [comment]
hi @ankitjain28may  yeah because the data is static , in every playlist and the first song is baarish song . and it starts playing playlist with the first song

**Comment by ankitjain28may** [comment]
@himanshukhosla123 ok no prb, BTW Great Work !

**Comment by himanshukhosla123** [comment]
Thanks bro @ankitjain28may
